{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "845c8771-6109-4df6-8db5-d429db48ff7b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/tristongrayston/anaconda3/envs/cooperative/bin/python\n",
      "1.9.0+cu102\n",
      "0.22.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "import sys, torch, gym\n",
    "print(sys.executable)     # should point into .../envs/cooperative/bin/python\n",
    "#print(marllib.__version__)   # 1.0.3\n",
    "print(torch.__version__)     # 1.9.0 (or whatever you installed)\n",
    "print(gym.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ea8bc1cb-b71b-446d-8975-7a7a1858c9a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import gym\n",
    "import time\n",
    "from gym.envs.registration import register\n",
    "import argparse\n",
    "import MARLlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7ac42a84-5466-4971-9ba2-bf364ba0a1b0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/gym/envs/registration.py:595: UserWarning: \u001b[33mWARN: Overriding environment multigrid-collect-v0\u001b[0m\n",
      "  logger.warn(f\"Overriding environment {id}\")\n"
     ]
    }
   ],
   "source": [
    "register(\n",
    "            id='multigrid-collect-v0',\n",
    "            entry_point='gym_multigrid.envs:CollectGame4HEnv10x10N2',\n",
    "        )\n",
    "env = gym.make('multigrid-collect-v0')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "40a41c77-489d-4733-89fb-cc95dbce1e72",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| Env_Name           | Check_Status   | Error_Log                                                            | Config_File_Location                         | Env_File_Location                   |\n",
      "+====================+================+======================================================================+==============================================+=====================================+\n",
      "| gymnasium_mamujoco | Error          | No module named 'gymnasium_robotics'                                 | envs/base_env/config/gymnasium_mamujoco.yaml | envs/base_env/gymnasium_mamujoco.py |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| mpe                | Ready          | Null                                                                 | envs/base_env/config/mpe.yaml                | envs/base_env/mpe.py                |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| gymnasium_mpe      | Error          | cannot import name 'simple_adversary_v3' from 'pettingzoo.mpe'       | envs/base_env/config/gymnasium_mpe.yaml      | envs/base_env/gymnasium_mpe.py      |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| mamujoco           | Error          | No module named 'multiagent_mujoco'                                  | envs/base_env/config/mamujoco.yaml           | envs/base_env/mamujoco.py           |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| smac               | Error          | No module named 'smac'                                               | envs/base_env/config/smac.yaml               | envs/base_env/smac.py               |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| football           | Error          | No module named 'gfootball'                                          | envs/base_env/config/football.yaml           | envs/base_env/football.py           |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| magent             | Error          | cannot import name 'adversarial_pursuit_v3' from 'pettingzoo.magent' | envs/base_env/config/magent.yaml             | envs/base_env/magent.py             |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| rware              | Error          | No module named 'rware'                                              | envs/base_env/config/rware.yaml              | envs/base_env/rware.py              |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| lbf                | Error          | No module named 'lbforaging'                                         | envs/base_env/config/lbf.yaml                | envs/base_env/lbf.py                |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| pommerman          | Error          | No module named 'pommerman'                                          | envs/base_env/config/pommerman.yaml          | envs/base_env/pommerman.py          |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| hanabi             | Error          | No module named 'cffi'                                               | envs/base_env/config/hanabi.yaml             | envs/base_env/hanabi.py             |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| metadrive          | Error          | No module named 'metadrive'                                          | envs/base_env/config/metadrive.yaml          | envs/base_env/metadrive.py          |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| mate               | Error          | No module named 'mate'                                               | envs/base_env/config/mate.yaml               | envs/base_env/mate.py               |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| gobigger           | Error          | No module named 'gobigger'                                           | envs/base_env/config/gobigger.yaml           | envs/base_env/gobigger.py           |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| overcooked         | Error          | No module named 'overcooked_ai_py'                                   | envs/base_env/config/overcooked.yaml         | envs/base_env/overcooked.py         |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| voltage            | Error          | No module named 'pandapower'                                         | envs/base_env/config/voltage.yaml            | envs/base_env/voltage.py            |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| aircombat          | Error          | No module named 'jsbsim'                                             | envs/base_env/config/aircombat.yaml          | envs/base_env/aircombat.py          |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| hns                | Error          | No module named 'mujoco_worldgen'                                    | envs/base_env/config/hns.yaml                | envs/base_env/hns.py                |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n",
      "| sisl               | Error          | cannot import name 'multiwalker_v7' from 'pettingzoo.sisl'           | envs/base_env/config/sisl.yaml               | envs/base_env/sisl.py               |\n",
      "+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+\n"
     ]
    }
   ],
   "source": [
    "from MARLlib.marllib import marl\n",
    "from ray import tune\n",
    "\n",
    "env = marl.make_env(environment_name=\"mpe\", map_name=\"simple_spread\", force_coop=True)\n",
    "\n",
    "mappo = marl.algos.mappo(hyperparam_source=\"test\", lr=tune.grid_search([0.0005, 0.001]))\n",
    "\n",
    "model = marl.build_model(env, mappo, {\"core_arch\": \"mlp\", \"encode_layer\": tune.grid_search([\"8-16\", \"16-32\"])})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "4346739f-567c-49e9-a203-288c577fca3e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 12:23:24,156\tWARNING worker.py:496 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ":task_name:bundle_reservation_check_func\n",
      ":actor_name:MAPPOTrainer\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 12:23:24,769\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "2025-05-26 12:23:24,770\tWARNING ppo.py:143 -- `train_batch_size` (50) cannot be achieved with your other settings (num_workers=1 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 50.\n",
      "2025-05-26 12:23:24,770\tINFO ppo.py:166 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.\n",
      "2025-05-26 12:23:24,770\tINFO trainer.py:770 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ":actor_name:RolloutWorker\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 12:23:25,059\tWARNING deprecation.py:38 -- DeprecationWarning: `SampleBatch['is_training']` has been deprecated. Use `SampleBatch.is_training` instead. This will raise an error in the future!\n",
      "2025-05-26 12:23:25,109\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:25,121\tWARNING trainer_template.py:185 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!\n",
      "2025-05-26 12:23:25,122\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:59: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:61: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:69: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "2025-05-26 12:23:25,127\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:25,135\tWARNING util.py:57 -- Install gputil for GPU system monitoring.\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py:39: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.\n",
      "  elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "[2025-05-26 12:23:25,147 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55eb0>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 591, in _env_runner\n",
      "    summarize(unfiltered_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "[2025-05-26 12:23:25,151 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55eb0>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 591, in _env_runner\n",
      "    summarize(unfiltered_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "2025-05-26 12:23:25,171\tWARNING util.py:165 -- The `start_trial` operation took 1.012 s, which may be a performance bottleneck.\n",
      "2025-05-26 12:23:25,187\tERROR trial_runner.py:924 -- Trial MAPPOTrainer_mpe_simple_spread_e44ca_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trial_runner.py\", line 890, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\", line 788, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55eb0>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 591, in _env_runner\n",
      "    summarize(unfiltered_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ":actor_name:MAPPOTrainer\n",
      "== Status ==\n",
      "Current time: 2025-05-26 12:23:25 (running for 00:00:01.15)\n",
      "Memory usage on this node: 2.8/15.3 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 2.0/16 CPUs, 1.0/1 GPUs, 0.0/8.21 GiB heap, 0.0/4.11 GiB objects\n",
      "Result logdir: /mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/exp_results/mappo_mlp_simple_spread\n",
      "Number of trials: 1/4 (1 RUNNING)\n",
      "+--------------------------------------------+----------+--------------------+--------+----------------------------------------------------------+\n",
      "| Trial name                                 | status   | loc                |     lr | model/custom_model_config/model_arch_args/encode_layer   |\n",
      "|--------------------------------------------+----------+--------------------+--------+----------------------------------------------------------|\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00000 | RUNNING  | 172.19.89.72:31119 | 0.0005 | 8-16                                                     |\n",
      "+--------------------------------------------+----------+--------------------+--------+----------------------------------------------------------+\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 12:23:25,839\tWARNING util.py:165 -- The `process_trial` operation took 0.653 s, which may be a performance bottleneck.\n",
      "2025-05-26 12:23:25,860\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "2025-05-26 12:23:25,861\tWARNING ppo.py:143 -- `train_batch_size` (50) cannot be achieved with your other settings (num_workers=1 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 50.\n",
      "2025-05-26 12:23:25,915\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:25,923\tWARNING trainer_template.py:185 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!\n",
      "2025-05-26 12:23:25,925\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:59: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:61: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:69: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "2025-05-26 12:23:25,931\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:25,940\tWARNING util.py:57 -- Install gputil for GPU system monitoring.\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py:39: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.\n",
      "  elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "[2025-05-26 12:23:25,949 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55e50>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 599, in _env_runner\n",
      "    _process_observations(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 818, in _process_observations\n",
      "    summarize(prep_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "[2025-05-26 12:23:25,951 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55e50>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 599, in _env_runner\n",
      "    _process_observations(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 818, in _process_observations\n",
      "    summarize(prep_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "2025-05-26 12:23:25,969\tERROR trial_runner.py:924 -- Trial MAPPOTrainer_mpe_simple_spread_e44ca_00001: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trial_runner.py\", line 890, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\", line 788, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55e50>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 599, in _env_runner\n",
      "    _process_observations(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 818, in _process_observations\n",
      "    summarize(prep_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ":task_name:bundle_reservation_check_func\n",
      ":actor_name:MAPPOTrainer\n",
      ":actor_name:RolloutWorker\n",
      ":actor_name:MAPPOTrainer\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 12:23:26,644\tWARNING util.py:165 -- The `process_trial` operation took 0.675 s, which may be a performance bottleneck.\n",
      "2025-05-26 12:23:26,664\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "2025-05-26 12:23:26,665\tWARNING ppo.py:143 -- `train_batch_size` (50) cannot be achieved with your other settings (num_workers=1 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 50.\n",
      "2025-05-26 12:23:26,711\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:26,719\tWARNING trainer_template.py:185 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!\n",
      "2025-05-26 12:23:26,719\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:59: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:61: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:69: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "2025-05-26 12:23:26,724\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:26,734\tWARNING util.py:57 -- Install gputil for GPU system monitoring.\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py:39: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.\n",
      "  elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "[2025-05-26 12:23:26,742 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efd7f7e80>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 599, in _env_runner\n",
      "    _process_observations(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 822, in _process_observations\n",
      "    logger.info(\"Filtered obs: {}\".format(summarize(filtered_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "[2025-05-26 12:23:26,745 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efd7f7e80>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 599, in _env_runner\n",
      "    _process_observations(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 822, in _process_observations\n",
      "    logger.info(\"Filtered obs: {}\".format(summarize(filtered_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "2025-05-26 12:23:26,763\tERROR trial_runner.py:924 -- Trial MAPPOTrainer_mpe_simple_spread_e44ca_00002: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trial_runner.py\", line 890, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\", line 788, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efd7f7e80>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 599, in _env_runner\n",
      "    _process_observations(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 822, in _process_observations\n",
      "    logger.info(\"Filtered obs: {}\".format(summarize(filtered_obs)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ":task_name:bundle_reservation_check_func\n",
      ":actor_name:MAPPOTrainer\n",
      ":actor_name:RolloutWorker\n",
      ":actor_name:MAPPOTrainer\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 12:23:27,437\tWARNING util.py:165 -- The `process_trial` operation took 0.675 s, which may be a performance bottleneck.\n",
      "2025-05-26 12:23:27,459\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "2025-05-26 12:23:27,460\tWARNING ppo.py:143 -- `train_batch_size` (50) cannot be achieved with your other settings (num_workers=1 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 50.\n",
      "2025-05-26 12:23:27,511\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:27,521\tWARNING trainer_template.py:185 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!\n",
      "2025-05-26 12:23:27,523\tWARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:59: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:61: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\n",
      "  warnings.warn(\"The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.\")\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:69: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\n",
      "  warnings.warn(\"The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.\")\n",
      "2025-05-26 12:23:27,528\tWARNING rollout_worker.py:578 -- You are running ray with `local_mode=True`, but have configured 1 GPUs to be used! In local mode, Policies are placed on the CPU and the `num_gpus` setting is ignored.\n",
      "2025-05-26 12:23:27,536\tWARNING util.py:57 -- Install gputil for GPU system monitoring.\n",
      "/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py:39: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.\n",
      "  elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "[2025-05-26 12:23:27,545 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55d90>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 622, in _env_runner\n",
      "    eval_results = _do_policy_eval(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 1017, in _do_policy_eval\n",
      "    summarize(to_eval)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 32, in _summarize\n",
      "    return [_summarize(x) for x in obj]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 32, in <listcomp>\n",
      "    return [_summarize(x) for x in obj]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 29, in _summarize\n",
      "    \"data\": _summarize(obj._asdict()),\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "[2025-05-26 12:23:27,548 E 31119 31119] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55d90>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 622, in _env_runner\n",
      "    eval_results = _do_policy_eval(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 1017, in _do_policy_eval\n",
      "    summarize(to_eval)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 32, in _summarize\n",
      "    return [_summarize(x) for x in obj]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 32, in <listcomp>\n",
      "    return [_summarize(x) for x in obj]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 29, in _summarize\n",
      "    \"data\": _summarize(obj._asdict()),\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations at time: 1.74829e+09\n",
      "2025-05-26 12:23:27,565\tERROR trial_runner.py:924 -- Trial MAPPOTrainer_mpe_simple_spread_e44ca_00003: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trial_runner.py\", line 890, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\", line 788, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/worker.py\", line 1625, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::MAPPOTrainer.train()\u001b[39m (pid=31119, ip=172.19.89.72, repr=MAPPOTrainer)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 679, in train\n",
      "    raise e\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\", line 668, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/trainable.py\", line 283, in train\n",
      "    result = self.step()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\", line 206, in step\n",
      "    step_results = next(self.train_exec_impl)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=31119, ip=172.19.89.72, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f7efdc55d90>)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 378, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 753, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 103, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 233, in get_data\n",
      "    item = next(self._env_runner)\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 622, in _env_runner\n",
      "    eval_results = _do_policy_eval(\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\", line 1017, in _do_policy_eval\n",
      "    summarize(to_eval)))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 20, in summarize\n",
      "    return _printer.pformat(_summarize(obj))\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 32, in _summarize\n",
      "    return [_summarize(x) for x in obj]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 32, in <listcomp>\n",
      "    return [_summarize(x) for x in obj]\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 29, in _summarize\n",
      "    \"data\": _summarize(obj._asdict()),\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in _summarize\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 25, in <dictcomp>\n",
      "    return {k: _summarize(v) for k, v in obj.items()}\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/rllib/utils/debug.py\", line 39, in _summarize\n",
      "    elif obj.dtype == np.object or obj.dtype.type is np.str_:\n",
      "  File \"/home/tristongrayston/anaconda3/envs/cooperative/lib/python3.8/site-packages/numpy/__init__.py\", line 305, in __getattr__\n",
      "    raise AttributeError(__former_attrs__[attr])\n",
      "AttributeError: module 'numpy' has no attribute 'object'.\n",
      "`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \n",
      "The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n",
      "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ":task_name:bundle_reservation_check_func\n",
      ":actor_name:MAPPOTrainer\n",
      ":actor_name:RolloutWorker\n",
      ":actor_name:MAPPOTrainer\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 12:23:28,241\tWARNING util.py:165 -- The `process_trial` operation took 0.676 s, which may be a performance bottleneck.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "== Status ==\n",
      "Current time: 2025-05-26 12:23:28 (running for 00:00:04.22)\n",
      "Memory usage on this node: 2.8/15.3 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 0/16 CPUs, 0/1 GPUs, 0.0/8.21 GiB heap, 0.0/4.11 GiB objects\n",
      "Result logdir: /mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/exp_results/mappo_mlp_simple_spread\n",
      "Number of trials: 4/4 (4 ERROR)\n",
      "+--------------------------------------------+----------+--------------------+--------+----------------------------------------------------------+\n",
      "| Trial name                                 | status   | loc                |     lr | model/custom_model_config/model_arch_args/encode_layer   |\n",
      "|--------------------------------------------+----------+--------------------+--------+----------------------------------------------------------|\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00000 | ERROR    | 172.19.89.72:31119 | 0.0005 | 8-16                                                     |\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00001 | ERROR    | 172.19.89.72:31119 | 0.001  | 8-16                                                     |\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00002 | ERROR    | 172.19.89.72:31119 | 0.0005 | 16-32                                                    |\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00003 | ERROR    | 172.19.89.72:31119 | 0.001  | 16-32                                                    |\n",
      "+--------------------------------------------+----------+--------------------+--------+----------------------------------------------------------+\n",
      "Number of errored trials: 4\n",
      "+--------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
      "| Trial name                                 |   # failures | error file                                                                                                                                                                                                         |\n",
      "|--------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00000 |            1 | /mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_e44ca_00000_0_lr=0.0005,encode_layer=8-16_2025-05-26_12-23-24/error.txt  |\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00001 |            1 | /mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_e44ca_00001_1_lr=0.001,encode_layer=8-16_2025-05-26_12-23-25/error.txt   |\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00002 |            1 | /mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_e44ca_00002_2_lr=0.0005,encode_layer=16-32_2025-05-26_12-23-26/error.txt |\n",
      "| MAPPOTrainer_mpe_simple_spread_e44ca_00003 |            1 | /mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_e44ca_00003_3_lr=0.001,encode_layer=16-32_2025-05-26_12-23-27/error.txt  |\n",
      "+--------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
      "\n"
     ]
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [MAPPOTrainer_mpe_simple_spread_e44ca_00000, MAPPOTrainer_mpe_simple_spread_e44ca_00001, MAPPOTrainer_mpe_simple_spread_e44ca_00002, MAPPOTrainer_mpe_simple_spread_e44ca_00003])",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "File \u001b[0;32m/tmp/ipykernel_31119/3760296984.py:1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mmappo\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43menv\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstop\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mtimesteps_total\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1000000\u001b[39;49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcheckpoint_freq\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m100\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mshare_policy\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mgroup\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/MARLlib/marllib/marl/__init__.py:316\u001b[0m, in \u001b[0;36m_Algo.fit\u001b[0;34m(self, env, model, stop, **running_params)\u001b[0m\n\u001b[1;32m    314\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m run_vd(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconfig_dict, env_instance, model_class, stop\u001b[38;5;241m=\u001b[39mstop)\n\u001b[1;32m    315\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39malgo_type \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCC\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m--> 316\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mrun_cc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconfig_dict\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43menv_instance\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmodel_class\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstop\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstop\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    317\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    318\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mnot supported type \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39malgo_type))\n",
      "File \u001b[0;32m/mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/MARLlib/marllib/marl/algos/run_cc.py:194\u001b[0m, in \u001b[0;36mrun_cc\u001b[0;34m(exp_info, env, model, stop)\u001b[0m\n\u001b[1;32m    188\u001b[0m exp_info, run_config, stop_config, restore_config \u001b[38;5;241m=\u001b[39m restore_config_update(exp_info, run_config, stop_config)\n\u001b[1;32m    190\u001b[0m \u001b[38;5;66;03m##################\u001b[39;00m\n\u001b[1;32m    191\u001b[0m \u001b[38;5;66;03m### run script ###\u001b[39;00m\n\u001b[1;32m    192\u001b[0m \u001b[38;5;66;03m##################\u001b[39;00m\n\u001b[0;32m--> 194\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[43mPOlICY_REGISTRY\u001b[49m\u001b[43m[\u001b[49m\u001b[43mexp_info\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43malgorithm\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m]\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mexp_info\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrun_config\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43menv_info\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstop_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    195\u001b[0m \u001b[43m                                                 \u001b[49m\u001b[43mrestore_config\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    197\u001b[0m ray\u001b[38;5;241m.\u001b[39mshutdown()\n\u001b[1;32m    199\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m results\n",
      "File \u001b[0;32m/mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/MARLlib/marllib/marl/algos/scripts/mappo.py:112\u001b[0m, in \u001b[0;36mrun_mappo\u001b[0;34m(model, exp, run, env, stop, restore)\u001b[0m\n\u001b[1;32m    109\u001b[0m RUNNING_NAME \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m_\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;241m.\u001b[39mjoin([algorithm, arch, map_name])\n\u001b[1;32m    110\u001b[0m model_path \u001b[38;5;241m=\u001b[39m restore_model(restore, exp)\n\u001b[0;32m--> 112\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[43mtune\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mMAPPOTrainer\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    113\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mname\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mRUNNING_NAME\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    114\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mcheckpoint_at_end\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mexp\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mcheckpoint_end\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    115\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mcheckpoint_freq\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mexp\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mcheckpoint_freq\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    116\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mrestore\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmodel_path\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    117\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mstop\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstop\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    118\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    119\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mverbose\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m    120\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mprogress_reporter\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mCLIReporter\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    121\u001b[0m \u001b[43m                   \u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mavailable_local_dir\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mexp\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mlocal_dir\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m==\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mexp\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mlocal_dir\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m results\n",
      "File \u001b[0;32m~/anaconda3/envs/cooperative/lib/python3.8/site-packages/ray/tune/tune.py:624\u001b[0m, in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, loggers, _remote)\u001b[0m\n\u001b[1;32m    622\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m incomplete_trials:\n\u001b[1;32m    623\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m raise_on_failed_trial \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m state[signal\u001b[38;5;241m.\u001b[39mSIGINT]:\n\u001b[0;32m--> 624\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m TuneError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrials did not complete\u001b[39m\u001b[38;5;124m\"\u001b[39m, incomplete_trials)\n\u001b[1;32m    625\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    626\u001b[0m         logger\u001b[38;5;241m.\u001b[39merror(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrials did not complete: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, incomplete_trials)\n",
      "\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [MAPPOTrainer_mpe_simple_spread_e44ca_00000, MAPPOTrainer_mpe_simple_spread_e44ca_00001, MAPPOTrainer_mpe_simple_spread_e44ca_00002, MAPPOTrainer_mpe_simple_spread_e44ca_00003])"
     ]
    }
   ],
   "source": [
    "mappo.fit(env, model, stop={\"timesteps_total\": 1000000}, checkpoint_freq=100, share_policy=\"group\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77c08fc8-2bca-4289-a0b6-941d3a5f693f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# A start and maybe a fun gif\n",
    "from ray.tune.registry import register_env\n",
    "from ray.rllib.env import PettingZooEnv\n",
    "from gym_multigrid.envs.soccer_game import SoccerGame4HEnv10x15N2\n",
    "from pettingzoo.utils import from_parallel as parallel_to_aec\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "e06b0cc2-4385-4e6c-9b6c-6a8af0cfdb89",
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: '/mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/MARLlib/marllib/marl/../envs/base_env/config/pettingzoo.yaml'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[17], line 13\u001b[0m\n\u001b[1;32m      9\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m PettingZooEnv(aec_env) \n\u001b[1;32m     11\u001b[0m register_env(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmultigrid_soccer\u001b[39m\u001b[38;5;124m\"\u001b[39m, multigrid_soccer_env)\n\u001b[0;32m---> 13\u001b[0m env \u001b[38;5;241m=\u001b[39m \u001b[43mmarl\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmake_env\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     14\u001b[0m \u001b[43m        \u001b[49m\u001b[43menvironment_name\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mpettingzoo\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m     \u001b[49m\u001b[38;5;66;43;03m# generic PettingZoo adapter\u001b[39;49;00m\n\u001b[1;32m     15\u001b[0m \u001b[43m        \u001b[49m\u001b[43mmap_name\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmultigrid_soccer\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m       \u001b[49m\u001b[38;5;66;43;03m# the Ray string we just registered\u001b[39;49;00m\n\u001b[1;32m     16\u001b[0m \u001b[43m        \u001b[49m\u001b[43mforce_coop\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m                    \u001b[49m\u001b[38;5;66;43;03m# optional: flip to full cooperation\u001b[39;49;00m\n\u001b[1;32m     17\u001b[0m \u001b[43m      \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/MARLlib/marllib/marl/__init__.py:98\u001b[0m, in \u001b[0;36mmake_env\u001b[0;34m(environment_name, map_name, force_coop, abs_path, **env_params)\u001b[0m\n\u001b[1;32m     93\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     94\u001b[0m     \u001b[38;5;66;03m# default config\u001b[39;00m\n\u001b[1;32m     95\u001b[0m     env_config_file_path \u001b[38;5;241m=\u001b[39m os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mjoin(os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mdirname(\u001b[38;5;18m__file__\u001b[39m),\n\u001b[1;32m     96\u001b[0m                                         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m../envs/base_env/config/\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m.yaml\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(environment_name))\n\u001b[0;32m---> 98\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43menv_config_file_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mr\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mas\u001b[39;00m f:\n\u001b[1;32m     99\u001b[0m     env_config_dict \u001b[38;5;241m=\u001b[39m yaml\u001b[38;5;241m.\u001b[39mload(f, Loader\u001b[38;5;241m=\u001b[39myaml\u001b[38;5;241m.\u001b[39mFullLoader)\n\u001b[1;32m    100\u001b[0m     f\u001b[38;5;241m.\u001b[39mclose()\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: '/mnt/c/Users/grays/OneDrive/Desktop/github things/CooperativeBehaviour/MARLlib/marllib/marl/../envs/base_env/config/pettingzoo.yaml'"
     ]
    }
   ],
   "source": [
    "\n",
    "def multigrid_soccer_env(config):\n",
    "    raw_env = SoccerGame4HEnv10x15N2()         # > implements the Parallel API\n",
    "    aec_env = parallel_to_aec(raw_env)         # > AEC that Ray understands\n",
    "    return PettingZooEnv(aec_env) \n",
    "\n",
    "register_env(\"multigrid_soccer\", multigrid_soccer_env)\n",
    "\n",
    "env = marl.make_env(\n",
    "        environment_name=\"pettingzoo\",     # generic PettingZoo adapter\n",
    "        map_name=\"multigrid_soccer\",       # the Ray string we just registered\n",
    "        force_coop=True                    # optional: flip to full cooperation\n",
    "      )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "a37c28c0-4b00-4039-900b-6d4f91873bbe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['__annotations__',\n",
       " '__call__',\n",
       " '__class__',\n",
       " '__closure__',\n",
       " '__code__',\n",
       " '__defaults__',\n",
       " '__delattr__',\n",
       " '__dict__',\n",
       " '__dir__',\n",
       " '__doc__',\n",
       " '__eq__',\n",
       " '__format__',\n",
       " '__ge__',\n",
       " '__get__',\n",
       " '__getattribute__',\n",
       " '__globals__',\n",
       " '__gt__',\n",
       " '__hash__',\n",
       " '__init__',\n",
       " '__init_subclass__',\n",
       " '__kwdefaults__',\n",
       " '__le__',\n",
       " '__lt__',\n",
       " '__module__',\n",
       " '__name__',\n",
       " '__ne__',\n",
       " '__new__',\n",
       " '__qualname__',\n",
       " '__reduce__',\n",
       " '__reduce_ex__',\n",
       " '__repr__',\n",
       " '__setattr__',\n",
       " '__sizeof__',\n",
       " '__str__',\n",
       " '__subclasshook__']"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dir(parallel_to_aec)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5083d3db-8fe4-455e-bf1f-6d4628dc07c2",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'env' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m _ \u001b[38;5;241m=\u001b[39m \u001b[43menv\u001b[49m\u001b[38;5;241m.\u001b[39mreset()\n\u001b[1;32m      2\u001b[0m nb_agents \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mlen\u001b[39m(env\u001b[38;5;241m.\u001b[39magents)\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m _ \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(\u001b[38;5;241m1\u001b[39m):\n\u001b[1;32m      5\u001b[0m     \u001b[38;5;66;03m#env.render(highlight=True)\u001b[39;00m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'env' is not defined"
     ]
    }
   ],
   "source": [
    "_ = env.reset()\n",
    "nb_agents = len(env.agents)\n",
    "\n",
    "for _ in range(1):\n",
    "    #env.render(highlight=True)\n",
    "    time.sleep(0.1)\n",
    "    \n",
    "    ac = [env.action_space.sample() for _ in range(nb_agents)]\n",
    "    #ac = [0] * nb_agents\n",
    "    \n",
    "    obs, _, done, _ = env.step(ac)\n",
    "    print(\"Num Agents = \", len(obs))\n",
    "    print(\"Obs shape = \", obs[0].T.shape)\n",
    "    \n",
    "    if done:\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "026a4956-3d10-45fe-a054-a19db61ae57e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Agent\n",
    "import numpy as np\n",
    "import argparse\n",
    "import gym\n",
    "from mappo.onpolicy.algorithms.r_mappo.r_mappo import R_MAPPO\n",
    "from mappo.onpolicy.algorithms.r_mappo.algorithm.rMAPPOPolicy import R_MAPPOPolicy as policy\n",
    "from mappo.onpolicy.config import get_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "48e9fbe4-39e0-4987-850d-7c5b35453203",
   "metadata": {},
   "outputs": [],
   "source": [
    "''' rMAPPOPolicy wants a centralized observation space as well. In this case, what we could do is output the whole grid, but that might\n",
    "cause some unnessessary strife here. It's probably easier in this case to just throw all of the observations into one array.'''\n",
    "\n",
    "obs_shape = obs[0].T.shape\n",
    "obs_shape = gym.spaces.Box(0, 32*32, obs_shape)\n",
    "\n",
    "action_space = gym.spaces.Discrete(3) # One hot encoded action space\n",
    "\n",
    "cent_obs_space = np.array([4, 6, 7, 7])\n",
    "cent_obs_space = gym.spaces.Box(0, 32*32, cent_obs_space)\n",
    "\n",
    "# Gets the default arguments for the policy in question\n",
    "parser = get_config()                        # build the ArgumentParser\n",
    "args   = parser.parse_args([])               # empty list ⇒ use every default\n",
    "#print(vars(args))\n",
    "\n",
    "p = policy(args, obs_space = obs_shape, cent_obs_space = cent_obs_space, act_space = action_space)\n",
    "agent = R_MAPPO(args, policy)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3627e1a-bc31-40f0-9bbc-dbee30b5de2a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (cooperative)",
   "language": "python",
   "name": "cooperative"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
